### ISSUE TITLE
JSON error when using package 

### ISSUE THREAD

**Issue by OregonianPyro** [RuyiLi/hastebin-generator#2]
Whenever I try to use the package in NodeJS it returns an error "unexpected token < in JSON at position 0" making it impossible to use the package. Worked fine earlier today.

**Comment by RuyiLi** [comment]
It seems this happens whenever hastebin stops working, which happens every once in a while. At the time of this comment, attempting to create a hastebin document manually on https://hastebin.com/ will give an error. 
![image](https://user-images.githubusercontent.com/16544254/45687342-8d5d9900-bb1c-11e8-99cb-8c71923d1e80.png)
As an alternative, you can use https://www.npmjs.com/package/nomsy-paste, which is essentially the same thing as hastebin except without the random crashes.
